<a href="https://colab.research.google.com/github/OlegKret/---/blob/master/Hopfild_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def calculate_weights(patterns):
    """Calculates the weight matrix for the Hopfield network."""
    num_patterns, num_neurons = patterns.shape
    weights = np.zeros((num_neurons, num_neurons))
    for pattern in patterns:
        weights += np.outer(pattern, pattern)
    np.fill_diagonal(weights, 0)  # Zero out the diagonal
    return weights / num_patterns

def retrieve_pattern(weights, distorted_pattern, max_iterations=100):
    """Retrieves a pattern from the Hopfield network with detailed reporting."""
    pattern = distorted_pattern.copy()
    report = []
    report.append("Initial State: " + str(pattern))

    for iteration in range(max_iterations):
        for i in range(len(pattern)):
            pattern[i] = np.sign(np.dot(weights[i], pattern))
        report.append(f"Iteration {iteration + 1}: " + str(pattern))
        if np.array_equal(pattern, distorted_pattern):
            report.append("Network converged.")
            break
        distorted_pattern = pattern.copy()

    return pattern, report

# Reference images
patterns = np.array([
    [1, 1, -1, -1, -1],
    [1, 1, 1, -1, 1]
])

# Distorted vector
distorted_pattern = np.array([1, 1, -1, -1, -1])

# Calculate weights
weights = calculate_weights(patterns)

# Retrieve pattern
retrieved_pattern, retrieval_report = retrieve_pattern(weights, distorted_pattern)

print("Weight Matrix:")
print(weights)

print("\nDetailed Retrieval Report:")
for line in retrieval_report:
    print(line)

print("\nFinal Retrieved Pattern:")
print(retrieved_pattern)

Weight Matrix:
[[ 0.  1.  0. -1.  0.]
 [ 1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  1.]
 [-1. -1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]

Detailed Retrieval Report:
Initial State: [ 1  1 -1 -1 -1]
Iteration 1: [ 1  1 -1 -1 -1]
Network converged.

Final Retrieved Pattern:
[ 1  1 -1 -1 -1]
